### ISSUE TITLE
Login fails after eboks2pop upgrade

### ISSUE THREAD

**Issue by hjstorner** [dk/Net-Eboks#3]
I've been re-installing my Debian box. As part of this I also updated eboks2pop to the latest code (fetched on Aug 13 2019). Did a clean re-install, built the Perl module. But login now fails:

fetchmail: Godkendelsesfejl på 010101-1234:XYZabcdef@localhost

(CPR-number and access code obfuscated). As you can see I use fetchmail to pick up the mail - the .fetchmailrc config is:

poll localhost
port 8110
with proto POP3
uidl
user "010101-1234:XYZabcdef"
there with password "password1"
is "henrik" here

The old version (from around july 2017, the Eboks.pm says version 0.03) actually works on the new system. Just copying the eboks2pop binary and the Eboks.pm perl module into the new installation can log in and appears to work OK. So it seems to be some sort of regression.

I tried registering via the web app on port 9999, but this also fails with a login error.

**Comment by dk** [comment]
Hey

The "user" format has changed due to the whole new shebang with the NemID authentication that is now required by eBoks. Now the fetchmail command would be

`user "111111223344"`

instead.

**Comment by hjstorner** [comment]
Hi,

thanks - but I am unsure what you mean: Should that be the CPR-number as the user? You wrote 12 digits, not 10, so not sure what you mean.

If I look at the example fetchmailrc (should have done that first - sorry) I see it has

user "000000-1234" there
with password "user1password"

so a CPR-number for the "user" setting. Is "user1password" the mobile access password?

And since you talk about NemID - does it matter if I have changed my NemID login name so it is not my CPR-number anymore?

I think I have tried all permutations of
* user = cpr-number
* user = my NemID login name
* password = the old mobile access password
* password = the mobile code 
* password = my NemID password

but it just won't work.

**Comment by dk** [comment]
Yes sorry CPR should be just 10 digits. Password is the mobile access password, yes. Also, it will only work now (without the 3rd mobile activation code) if you have activated the NemID access. As for the NemID login name, I have no idea whether the name change bears any effect here. Please check out the docs about NemID auth, it's more complex now
