### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by DDHF22** [dk/Net-Eboks#6]
Not really an issue but merely a status request for the module before polluting windows with yet another ecosystem (perl) :-)

Will Net-Eboks still run on Windows (with perl) after eboks moved to MitId ?

Thanks

**Comment by dk** [comment]
Judt checked, still works on authenticated setup. The authentication itself though could be broken if eboks completely removes nemid; last time I checked several months ago when both nemid and mitid were available as auth option, mitid auth didn't work but nemid auth did. 

Related, there is https://github.com/dk/Net-MitDK for Digital Post, although I do get some mails on eboks only. I couldn't figure out how to migrate completely to mit.dk, not that I tried much though..
